# Generated by Django 3.2.8 on 2022-05-01 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 1, 12, 26, 28, 284238)),
        ),
    ]
